print("PPPPPPP                L")
print("P       P              L")
print("P         P            L")
print("P        P             L")
print("PPPPPPP                L")
print("P                      L")
print("P                      L")
print("P                      LLLLLLLLLLLL")
